stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
      - data/raw/churn_data.csv
      - src/preprocess.py
    outs:
      - data/processed/X_train.csv
      - data/processed/y_train.csv
      - models/preprocessor.pkl
  train:
    cmd: python src/train.py
    deps:
      - data/processed/X_train.csv
      - data/processed/y_train.csv
      - models/preprocessor.pkl
      - src/train.py
    outs:
      - models/model.pkl